---
server:
  hosts:
    gros-104.nancy.grid5000.fr:
targets:
  hosts:
    gros-107.nancy.grid5000.fr:
    gros-108.nancy.grid5000.fr:
    gros-110.nancy.grid5000.fr:
    gros-111.nancy.grid5000.fr:
    gros-114.nancy.grid5000.fr:
    gros-16.nancy.grid5000.fr:
    gros-32.nancy.grid5000.fr:
    gros-44.nancy.grid5000.fr:
    gros-49.nancy.grid5000.fr:
    gros-61.nancy.grid5000.fr:
clients:
  hosts:
    gros-62.nancy.grid5000.fr:
    gros-63.nancy.grid5000.fr:
    gros-64.nancy.grid5000.fr:
    gros-66.nancy.grid5000.fr:
    gros-67.nancy.grid5000.fr:
    gros-68.nancy.grid5000.fr:
    gros-7.nancy.grid5000.fr:
    gros-75.nancy.grid5000.fr:
    gros-83.nancy.grid5000.fr:
    gros-99.nancy.grid5000.fr:
wg:
  children:
    server:
    clients:
