all:
  vars:
    root_dir: "~/wireguard-experiment"
    keypairs: "{{ lookup('file', '../static/keypairs.json') | from_json }}"
    index: "{{ lookup('file', '../static/index.json') | from_json }}"
    target_index: "{{ lookup('file', '../static/target_index.json') | from_json }}"
    server_keypairs: "{{ lookup('file', '../static/server_keypairs.json') | from_json }}"
    server_address: "{{ hostvars[groups['server'][0]]['ansible_facts']['default_ipv4']['address'] }}"
    username_server: root
    username_client: root
    username_target: root
    username: root
    iface: eno1 # eno1 for nancy and ens10f0np0 for rennes 
    n_clients: 1000
    batch: 100

    limited_bandwidth: false
    limit_bandwidth: 30mbit

    bandwidth_varying: False
    bandwidth_list: 1G 3G 6G 9G 12G 15G 20G 22G 25G
    wg_activated: True
    is_personal: False
    script_path: "/tmp/scripts"
    results_path: "/tmp/results"
    ftrace_path: "/sys/kernel/debug/tracing"
    
