all:
  vars:
    root_dir: "~/wireguard-experiment"
    keypairs: "{{ lookup('file', 'keypairs.json') | from_json }}"
    index: "{{ lookup('file', 'index.json') | from_json }}"
    target_index: "{{ lookup('file', 'target_index.json') | from_json }}"
    server_keypairs: "{{ lookup('file', 'server_keypairs.json') | from_json }}"
    server_address: "{{ hostvars[groups['server'][0]]['ansible_facts']['default_ipv4']['address'] }}"
    # target_address: "{{ hostvars[groups['target'][0]]['ansible_facts']['default_ipv4']['address'] }}"
    username_server: root
    username_client: root
    username_target: root
    username: root
    n_clients: 1000
    runs: 3
    batch: 100

    ncore_set: "36"
    nflow_set: "1 2 10 40 50 80 100"
    unit_time_s: 70

    bandwidth_varying: False
    bandwidth_list: 1G 3G 6G 9G 12G 15G 20G 22G 25G
    wg_activated: True
    is_personal: False
    script_path: "/tmp/scripts"
    results_path: "/tmp/results"
    ftrace_path: "/sys/kernel/debug/tracing"