---
- name: Install all dependencies on server
  hosts: all
  remote_user: "{{ username_server }}"
  gather_facts: false

  tasks:
    - name: Install the dependencies
      apt:
        name: [git, zip, ethtool, linux-cpupower, zstd, bc, curl, tree, trace-cmd, sysstat, iptables, wireguard, iperf3, dnsutils, netperf, bc, nginx, apache2, traceroute, iftop, htop, tcpdump, net-tools, iproute2, psmisc, tree, linux-perf, make, build-essential, dwarves, linux-headers-6.1.0-30-amd64, perl, automake, autoconf, m4, libtool-bin, openssl]
        state: present
    # - name : Install flame graph
    #   git:
    #     repo: https://github.com/brendangregg/FlameGraph.git
    #     dest: /tmp/scripts/FlameGraph
    #     force: true
    - name: Enable sysstat monitoring
      shell: systemctl enable sysstat; systemctl start sysstat
    - name: Download cargo
      shell:  curl https://sh.rustup.rs -sSf > cargo-install.sh
    - name: Make cargo installer script runnable
      shell: chmod +x cargo-install.sh
    - name: Install cargo through cargo installer script
      shell: ~/cargo-install.sh -y
