---
- name: Deactivate wireguard interfaces on clients
  hosts: clients
  remote_user: "{{ username_client }}"
  gather_facts: false

  tasks:
    - name: Deactivate Wireguard conf
      shell:
        cmd: for i in `ls confs`; do wg-quick down confs/$i ; done

- name: Deactivate wireguard interfaces on server 
  hosts: server
  remote_user: "{{ username_server }}"
  gather_facts: false

  tasks:
    - name: Deactivate Wireguard conf
      shell:
        cmd: for i in `ls confs`; do wg-quick down confs/$i ; done

- name: Include Wireguard Setup playbook
  import_playbook: "setup-wireguard.yml"

- name: Include network configuration playbook
  import_playbook: "setup-network.yml"
