---
- name: "Generate conf files for server"
  hosts: server
  tasks:
    - name: run wg_gen.py script for server config generation
      shell: | 
        /tmp/scripts/wg_gen.py \
          -k keypairs.json \
          -b {{ batch }} \
          -s server_keypairs.json \ 
          -n {{ n_clients }} \
          -o confs \
          {% if is_personal %} -m {% endif %} \
          {% if wg_userspace %} -u {% endif %}

- name: "Generate conf files for server"
  hosts: clients
  tasks:
    - name: Generate conf files for clients
      shell: |
        /tmp/scripts/wg_gen.py \
          -k keypairs.json \
          -s server_keypairs.json \
          -n {{ batch }} \
          -i {{ index[ansible_hostname] }} \
          {% if is_personal %} -m {% endif %} \
          -o confs \
          -d {{ server_address }}
  
- name: Activate wireguard interfaces on wireguard clients 
  hosts: clients
  remote_user: "{{ username_client }}"

  tasks:
    - name: Activate Wireguard conf on clients
      shell:
        cmd: for i in `ls confs`; do wg-quick up confs/$i ; done
      ignore_errors: true

- name: Activate wireguard interfaces on server 
  hosts: server
  remote_user: "{{ username_server }}"
  gather_facts: false

  tasks:
    - name: Activate server config
      shell: /tmp/scripts/activate_wg.sh