---
- name: Apply necessary network configuration on server 
  hosts: server
  remote_user: "{{ username_server }}"
  gather_facts: true
  tasks:
    - name: Enable Ipv4 forwarding
      shell:
        cmd: sysctl net.ipv4.ip_forward=1

- name: Launch http server on targets
  hosts: targets
  remote_user: "{{ username_server }}"
  gather_facts: true
  tasks:
    - name: Initialize server's network configuration
      shell:
        cmd: /tmp/scripts/init_server.sh
      ignore_errors: true

- name: Apply necessary network configuration on clients 
  hosts: clients
  remote_user: "{{ username_client }}"
  gather_facts: true

  tasks:
    - name: Add route to target
      ignore_errors: true
      shell: 
        cmd: ip route add {{ hostvars[target_index[ansible_nodename]]['ansible_default_ipv4']['address'] }} via {{ server_address }}
    - name: Enable Ipv4 forwarding
      shell:
        cmd: sysctl net.ipv4.ip_forward=1

- name: Limit bandwidth on clients
  hosts: clients
  remote_user: "{{ username_client }}"
  gather_facts: false

  tasks:
    - name: Apply limit_bandwidth on clients
      shell: /tmp/scripts/limit_bandwidth.sh
      ignore_errors: True
