---
- name: Send necessary files to server 
  hosts: server
  remote_user: "{{ username_server }}"
  gather_facts: false

  tasks:
    - name: Send wrk binary
      copy:
        src: ../templates/wrk
        dest: /usr/bin/wrk
    - name: Send activate_wg.sh script
      template:
        src: ../templates/activate_wg.sh.jinja
        dest: /tmp/scripts/activate_wg.sh
    - name: Send client keypairs         
      template:
        src: ../static/keypairs.json
        dest: keypairs.json                  
    - name: Send server keypairs         
      template:
        src: ../static/server_keypairs.json          
        dest: server_keypairs.json
    - name: Send cpu_set.sh
      template:
        src: ../templates/cpu_set.sh
        dest: /tmp/scripts/cpu_set.sh
    - name: Send wireguard conf generator
      template:
        src: ../templates/wg_gen_server_conf.py
        dest: /tmp/scripts/wg_gen.py
    - name: Send wg_test_decrypt_worker_analysis.sh
      template:
        src: ../templates/wg_test_decrypt_worker_analysis.sh
        dest: /tmp/scripts/wg_test_decrypt_worker_analysis.sh
    - name: Send wg_test_tx_worker_analysis.sh
      template:
        src: ../templates/wg_test_tx_worker_analysis.sh
        dest: /tmp/scripts/wg_test_tx_worker_analysis.sh
    - name: Send wg_test_scheduler_analysis.sh
      template:
        src: ../templates/wg_test_scheduler_analysis.sh
        dest: /tmp/scripts/wg_test_scheduler_analysis.sh
    - name: Send rx poll test
      template:
        src: ../templates/wg_test_rx_poll_analysis.sh
        dest: /tmp/scripts/wg_test_rx_poll_analysis.sh
    - name: Send wg_test_function_execution_time.sh
      template:
        src: ../templates/wg_test_function_execution_time.sh
        dest: /tmp/scripts/wg_test_function_execution_time.sh
    - name: Send wg_test_trace_printk.sh
      template:
        src: ../templates/wg_test_trace_printk.sh
        dest: /tmp/scripts/wg_test_trace_printk.sh
    - name: Send wg_test_trace_printk.sh
      template:
        src: ../templates/wg_test_perf.sh
        dest: /tmp/scripts/wg_test_perf.sh
    - name: Send wg_test_global_perf.sh
      template:
        src: ../templates/wg_test_global_perf.sh
        dest: /tmp/scripts/wg_test_global_perf.sh
    - name: Send wg_test_cpu_pidstat.sh
      template:
        src: ../templates/wg_test_cpu_pidstat.sh
        dest: /tmp/scripts/wg_test_cpu_pidstat.sh
    - name: Send test.sh script
      template:
        src: ../templates/test.sh.jinja
        dest: /tmp/scripts/test.sh
    - name: Make all scripts executable
      shell:
        cmd: chmod +x -R /tmp/scripts


- name: Send necessary files to clients 
  hosts: clients
  remote_user: "{{ username_client }}"
  gather_facts: false

  tasks:
    - name: Send wrk binary
      copy:
        src: ../templates/wrk
        dest: /usr/bin/wrk
    - name: Send activate_wg.sh script
      template:
        src: ../templates/activate_wg_client.sh.jinja
        dest: /tmp/scripts/activate_wg.sh
    - name: Send scp benchmark script
      template:
        src: ../templates/benchmark_scp.sh.jinja
        dest: /tmp/scripts/benchmark_scp.sh
    - name: Send script for sockperf installation
      template:
        src: ../templates/install_sockperf.sh
        dest: /tmp/scripts/install_sockperf.sh 
    - name: Send sockperf binary 
      copy:
        src: ../templates/sockperf
        dest: /tmp/sockperf 
    - name: Send client keypairs
      template:
        src: ../static/keypairs.json
        dest: keypairs.json
    - name: Send server keypairs
      template:
        src: ../static/server_keypairs.json
        dest: server_keypairs.json
    - name: Send client generator script
      template:
        src: ../templates/client_gen.sh.jinja
        dest: /tmp/scripts/test.sh
    - name: Send limit_bandwidth script
      template:
        src: ../templates/limit_bandwidth.sh.jinja
        dest: /tmp/scripts/limit_bandwidth.sh
    - name: Send unlimit_bandwidth script
      template:
        src: ../templates/unlimit_bandwidth.sh
        dest: /tmp/scripts/unlimit_bandwidth.sh
    # - name: Send HEY script
    #   template:
    #     src: ../templates/hey_linux_amd64
    #     dest: /tmp/scripts/hey_linux_amd64
    - name: Send wireguard conf generator
      template:
        src: ../templates/wg_gen_client_conf.py
        dest: /tmp/scripts/wg_gen.py
    - name: Make all scripts executable
      shell:
        cmd: chmod +x -R /tmp/scripts

- name: Send necessary files to targets
  hosts: targets
  remote_user: "{{ username_target }}"
  gather_facts: false

  tasks:
    - name: Send netserver launcher
      template:
        src: ../templates/launch_netserver.sh.jinja
        dest: /tmp/scripts/test.sh
    - name: Send nginx server config file
      copy:
        src: ../templates/nginx-server.conf
        dest: /etc/nginx/nginx.conf
        force: true
    - name: Send hls video file
      copy:
        src: ../templates/hls-video.zip
        dest: /tmp/scripts/hls-video.zip
        force: true
    - name: Send dash video file
      copy:
        src: ../templates/dash-video.zip
        dest: /tmp/scripts/dash-video.zip
    - name: Send nginx config script
      copy:
        src: ../templates/configure_nginx.sh
        dest: /tmp/scripts/configure_nginx.sh
    - name: Send init_server.sh script
      template:
        src: ../templates/init_server.sh
        dest: /tmp/scripts/init_server.sh
    - name: Send script for sockperf installation
      template:
        src: ../templates/install_sockperf.sh
        dest: /tmp/scripts/install_sockperf.sh
    - name: Send sockperf binary 
      copy:
        src: ../templates/sockperf
        dest: /tmp/sockperf
    - name: Send TARGETS list
      template:
        src: ../EXPERIMENT_DATA/TARGETS
        dest: /tmp/scripts/TARGETS
    - name: Send NWEB lightweight http server
      template:
        src: ../templates/nweb
        dest: /tmp/scripts/nweb
    - name: Send Index file of 1M
      template:
        src: ../templates/index.html.1M
        dest: /var/www/html/file_1M.html
    - name: Send Index file of 100K
      template:
        src: ../templates/index.html.100K
        dest: /var/www/html/file_100K.html
    - name: Send Index file of 10K
      template:
        src: ../templates/index.html.10K
        dest: /var/www/html/file_10K.html
    - name: Send Index file of 1K
      template:
        src: ../templates/index.html.1K
        dest: /var/www/html/file_1K.html
    - name: Make all scripts executable
      shell: chmod +x -R /tmp/scripts

- name: Send and install self signed ssl certificates to all 
  hosts: all
  remote_user: "{{ username_server }}"
  gather_facts: false

  tasks:
    - name: Send ssl certificates
      copy:
        src: ../static/ssl-certs
        dest: /etc/nginx/
    - name: Install ssl certificates
      shell: "cp /etc/nginx/ssl-certs/nginx.crt /usr/local/share/ca-certificates/nginx.crt && update-ca-certificates"

- name: Install Sockperf on clients and targets
  hosts: [clients, targets]
  remote_user: "{{ username_server }}"
  gather_facts: false

  tasks:
    - name: Launch sockperf installation script
      shell: /tmp/scripts/install_sockperf.sh
  
- name: Resend test script to targets
  hosts: targets
  remote_user: "{{ username }}"
  gather_facts: true

  tasks:
    - name: Send netserver launcher
      template:
        src: ../templates/launch_netserver.sh.jinja
        dest: /tmp/scripts/test.sh
